### ISSUE TITLE
試作品の作成

### ISSUE THREAD

**Issue by dictav** [WatanabeSeisakujo/HeadPhoneAmp#3]

**Comment by fcnt** [comment]
今週土曜のNDSでアナウンスできるよう、土曜までに試作品を作ります。(コミット)

**Comment by dictav** [comment]
お、すごい！

**Comment by fcnt** [comment]
と、言う訳で当日のアナウンスお願いしますw

**Comment by fcnt** [comment]
試作品を設計していて色々と考えましたが、やはり電源は安全性の面から電池式にしたいです。

USBなど外部給電式では、配線間違いなどで異常に電流が流れた時にUSB電源側を壊してしまう可能性があります。電池であれば危険なほどの大電流は流れないので安全です。また、壊したとしても機器側だけで済むので被害は小さいです。USB電源化は回路をキチンと理解した人の応用編とした方が良いと思います。

**Comment by dictav** [comment]
USB化は充電式の角電池がないということで、モバイルバッテリーを使えば良いのではないかという話が元だったと思います。
さきほど検索してみたら、角電池も充電式があるようなので、ちょっと真面目に使いたくなった人にも対応できそうです。
電池式にしましょう。
- リチウムイオン角電池 (8V/600mAh) http://www.amazon.co.jp/PLATA-006P-Li-ion-リチウムイオン-600mAh/dp/B008H1KN0G/ref=pd_bxgy_e_img_z#customerReviews
- ニッケル水素電池 (8.4V/200mAh) http://www.amazon.co.jp/充電式IMPULSE-充電池-ニッケル水素電池-6P形-6TNH22A/dp/B007FMXF6C/ref=pd_bxgy_e_img_z
- 充電器 http://www.amazon.co.jp/東芝-TOSHIBA-TNHC-622SC-充電式IMPULSE-6P形専用充電器/dp/B007S944JO/ref=pd_bxgy_e_img_y

ref #4
