### ISSUE TITLE
ワークショップの物品の調達

### ISSUE THREAD

**Issue by dictav** [WatanabeSeisakujo/HeadPhoneAmp#4]
## スプレッドシート

https://docs.google.com/spreadsheets/d/1PuHFX_QBUyu_fTqXgYrjSceQES6sC6mzNuXGQp4NJRQ/edit#gid=0
## 備忘録
- ケーブル
  - 単芯のLANケーブルを解いて利用
  - 各員渡されたケーブルをちょうど良い長さに切って被覆を向いて利用する
- 箱は透明なタッパー
  - ~~千枚通し~~ドリルで穴あけ（ドリルMain: fcnt / ドリルSub: dictav)
  - パンチ (daiquiri99)
- 角電池（100円均一)
- バッテリースナップ

cc @fcnt @daiquiri99

**Comment by fcnt** [comment]
> 各員渡されたケーブルをちょうど良い長さに切って被覆を向いて利用する

ケーブルにLANケーブルを利用するのは良いと思いますが、
LANケーブルの中の線の被覆は断線しにくくするために滑りやすい被覆のため、
ワイヤーストリッパーのような専用工具でなければ剥くのにコツが要ります。
ワイヤーストリッパー1本あたり2800円しますが、工具の手配はどうしますか?
(100円で売っているワイヤーストリッパーでは配線が細すぎて使えないと思います。)

> 箱は透明なタッパー
>    千枚通しで穴あけ

これは無理です。タッパーに千枚通し、キリでは穴は空きません。
(空いてもきれいにはなりません。)
穴あけにはドリルが必要です。

一度考えたプランで各自試作して作業ボリュームの感覚を掴んでください。

**Comment by dictav** [comment]
了解です。被覆について向く回数が割と多いので、ワイヤーストリッパは複数必要になりますね。
ただ、ワイヤーストリッパをぼくらが必要もない数揃えるのは流石にオーバーだと思います。一度ケーブルを購入して加工のしやすさなど試してみるので、それで決めさせてください。

> タッパーに千枚通し、キリでは穴は空きません。

ではドリルですね。これについては、穴を開けるのは一箇所だと思うので、順番に開けてもらう形で良いと思います。
ぼくの部屋にあるドリルで問題ないでしょうか？

**Comment by fcnt** [comment]
ワイヤーストリッパーの件は了解です。僕も1本持っているので提供可能です。

ドリルの件ですが、穴あけには十分と思いますが出力がかなり強いので、使用する際は誰か横で見ていないといけないかもしれません。僕が1本電池式の電動ドリルを持っているので、それも提供可能です。(そちらをメインにした方が良いかもしれません。)

**Comment by dictav** [comment]
了解です。
ではそちらのドリルを使うことにして、ぼくのは予備として持って行く感じにしましょう。

**Comment by dictav** [comment]
角電池とバッテリースナップを物品に追加しました。
また、穴あけに使えそうなパンチを daiquiri99 さんが貸し出しできそうです。

**Comment by dictav** [comment]
ムサシで購入したUTPケーブルについて検証しました。
カッターでも簡単に被覆をむくことができたので、採用で良いと思います。

**Comment by fcnt** [comment]
わかりました、ではUTPケーブルを各自で加工してもらうと言う事にしましょう。

**Comment by dictav** [comment]
休みなくてシールド線とケースをまだ購入していません。
明日の朝購入します。
